// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFhOWhk_tjlKVxrRUTi5uWOUooTPK89E',
    appId: '1:153379569318:web:YOUR_WEB_APP_ID',
    messagingSenderId: '153379569318',
    projectId: 'vencceja-e8a9c',
    authDomain: 'vencceja-e8a9c.firebaseapp.com',
    storageBucket: 'vencceja-e8a9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFhOWhk_tjlKVxrRUTi5uWOUooTPK89E',
    appId: '1:153379569318:android:cbc42e17baf7aa328cfe67',
    messagingSenderId: '153379569318',
    projectId: 'vencceja-e8a9c',
    storageBucket: 'vencceja-e8a9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuFhOWhk_tjlKVxrRUTi5uWOUooTPK89E',
    appId: '1:153379569318:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '153379569318',
    projectId: 'vencceja-e8a9c',
    storageBucket: 'vencceja-e8a9c.firebasestorage.app',
    iosBundleId: 'com.company.vencceja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuFhOWhk_tjlKVxrRUTi5uWOUooTPK89E',
    appId: '1:153379569318:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '153379569318',
    projectId: 'vencceja-e8a9c',
    storageBucket: 'vencceja-e8a9c.firebasestorage.app',
    iosBundleId: 'com.company.vencceja',
  );
}
